version: '3.3'
volumes:
  mysql-db:
    driver: local
services:
  mysql:
    build: ../database/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_DATABASE: skillMgr
      MYSQL_USER: skillMgr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    networks:
      - "skill-mgr-system-net"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
  discovery:
    image: docker.pkg.github.com/sun-project/discovery/discovery
    networks:
      - "skill-mgr-system-net"
    ports:
      - "8761:8761"
  gateway:
    image: docker.pkg.github.com/sun-project/gateway/gateway
    networks:
      - "skill-mgr-system-net"
    ports:
      - "80:8080"
  skill-mgr-api:
    image: docker.pkg.github.com/sun-project/skill-mgr-api/skill-mgr-api
    networks:
      - "skill-mgr-system-net"
    ports:
      - "8081:8081"
#  skill-mgr-ui:
#    image: docker.pkg.github.com/sun-project/skill-mgr-ui/skill-mgr-ui
#    networks:
#      - "skill-mgr-system-net"
#    ports:
#      - "3000:3000"
networks:
  skill-mgr-system-net:
    driver: bridge
